src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     * @Assert\NotBlank(message="Il titolo non può essere vuoto")
     * @Assert\Length(min=5,max=20)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="La descrizione breve non può essere vuota")
     * @Assert\Length(max=50)
     */
    private $short_description;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Il testo non può essere vuoto")
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image(maxSize="100k")
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="blogs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="blogs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="apple-touch-icon" sizes="57x57" href="/img/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/img/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/img/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/img/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/img/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/img/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/img/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/img/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/img/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/img/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/img/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/img/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    {# Run `composer require symfony/webpack-encore-bundle`
    and uncomment the following Encore helpers to start using Symfony UX #}
    {% block stylesheets %}
    <link href='/css/custom.css' rel='stylesheet' type='text/css'>
    {% endblock %}

    {% block javascripts %}
    {#{{ encore_entry_script_tags('app') }}#}
    {% endblock %}
</head>

<body class="d-flex flex-column">
    {% include('navbar.html.twig') %}
    {% block body %}
    {% endblock %}
    {% include('footer.html.twig') %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
</body>

</html>

templates/footer.html.twig
<footer class="mt-auto text-center">
    <div>
        Icons made by&nbsp;<a href="https://www.freepik.com">Freepik</a>
        and
        <a href="https://www.flaticon.com/authors/becris" title="Becris">Becris</a>
        from&nbsp;<a href="https://www.flaticon.com/">www.flaticon.com</a>
        
    </div>
</footer>

templates/list.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="container-fluid mx-2">

    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    <div class="form-group d-flex align-items-center justify-content-between row mt-4">
        {{ form_label(form.category, 'Category:', {'attr': {'class': 'col-sm-2 col-form-label'}}) }}
        <div class="col-sm-10">
            {{ form_widget(form.category)}}
        </div>
        <div class="col-sm-1">
            {{ form_widget(form.submit)}}
        </div>
    </div>

    {{ form_end(form) }}
    <div class="row mt-2 d-flex justify-content-around">

        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="flash-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}

        {% if blogs %}
            {% for blog in blogs %}
                <div class="card mb-4" style="width: 18rem;">
                    {% if blog.image %}
                        {# immagine trovata, visualizzala #}
                        <img src="/img/{{blog.image}}" class="" alt="{{blog.title}}">
                    {% else %}
                        {# immagine non trovata, visualizza immagine default #}
                        <img src="/img/default.png" class="img-fluid rounded" alt="Default image">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{blog.title}}</h5>
                        <p class="card-text">{{blog.shortDescription}}</p>
                        <a href="{{path('app_blog_read', {id: blog.id})}}" class="btn btn-primary">Read more</a>
                        <a href="{{path('app_main_editblog', {id: blog.id})}}" class="btn btn-primary">Edit</a>
                        <a href="{{path('app_blog_read', {id: blog.id})}}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        There are no blogs in this category
        {% endif %}

    </div>
</div>


{% endblock %}

templates/navbar.html.twig
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{path('app_main_index')}}">Blogs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{path('app_main_index')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% for category in categories.getAll %}
                     <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_blog_list', {'category': category.name}) }}">{{category.name}}</a>
                    </li>
                {% endfor %}
                <li class="nav-item">
                    <a class="btn btn-primary ml-2" href="{{ path('app_blog_create') }}">Write a new blog</a>
                </li>
            </ul>
            {% if app.user %}
            <div class="dropdown">
                
                <a class="dropdown-toggle text-white text-decoration-none" id="dropdownMenuToggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if app.user.profilePicture %}
                    <img class="rounded-circle" src="/img/users/{{app.user.profilePicture}}" width="32px" height="32px" >
                {% else %}
                    <img class="rounded-circle" src="/img/users/default.png" width="32px" height="32px" >
                {% endif %}
                    
                </a>
                
                <div class="dropdown-menu dropdown-menu-left dropdown-menu-lg-right" aria-labelledby="dropdownMenuToggle">
                    {# TODO: implement profile and blogs pages #}
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="{{ path('app_user_blogs', {id: app.user.id}) }}">My blogs</a>
                    <a class="dropdown-item text-danger" href="{{ path('app_logout') }}">Logout</a>
                </div>
            </div>
            {% else %}
            <a class="btn btn-success my-2 mr-sm-2 my-sm-0" href="{{ path('app_login') }}">Login</a>
            <a class="btn btn-primary my-2 my-sm-0" href="{{ path('app_register') }}">Register</a>
            {% endif %}
        </div>
    </nav>
</header>

templates/read.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron mt-4">
        <h1 class="display-4">{{blog.title}} - {{blog.category.name}}</h1>
        <p class="lead">{{blog.shortDescription}}</p>
        <hr class="my-4">
        <p></p>
        {% if blog.image %}
        {# immagine trovata, visualizzala #}
        <img src="../img/{{blog.image}}" class="" alt="{{blog.title}}">
        {% else %}
        {# immagine non trovata, visualizza immagine default #}
        <img src="../img/default.png" class="img-fluid rounded" alt="Default image">
        {% endif %}
        <p class="mt-2">{{blog.body}}</p>
    </div>
    
{% endblock %}